on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    
    - name: Login
      uses: actions-hub/docker/login@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}  
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  

    - name: Build
      uses: okteto/actions/build@v1
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
        tag: ${{ secrets.DOCKER_USERNAME }}/action-test:${{ github.sha }}

    - name: Get Kubeconfig
      uses: okteto/actions/namespace@v1
      id: namespace
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
        namespace: tullo
    
    - name: Deploy and Wait
      uses: okteto/actions/deploy@v1
      env:
        KUBECONFIG: ${{ steps.namespace.outputs.kubeconfig }}  
      with:
        namespace: tullo
        manifest: k8s.yml
        tag: ${{ secrets.DOCKER_USERNAME }}/action-test:${{ github.sha }}
        waitOn: deployment/action-test
    
    - name: Verify
      uses: srt32/uptime@master
      with:
        url-to-hit: "https://action-test-tullo.cloud.okteto.net/"
        expected-statuses: "200"